import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FooterPage from "@/components/footer/FooterPage";
import HeaderPage from "@/components/header/HeaderPage";
import localFont from 'next/font/local'

const myFont = localFont({
  src: '../fonts/BeniRegular.woff2',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={myFont.className}>
        <HeaderPage />
        {children}
        <FooterPage />
      </body>
      
    </html>
  );
}
